#!/bin/bash

set -e

echo "Waiting for Django to apply migrations..."
until python manage.py showmigrations | grep '\[X\]'; do
    sleep 1
done

>&2 echo 'Django Celery migrations have been applied'

exec "$@"
